language: php
php:
  - nightly

env:
  - CC=clang   CFLAGS=""
  - CC=clang   CFLAGS="-g -O0"
  - CC=gcc-4.6 CFLAGS=""
  - CC=gcc-4.6 CFLAGS="-g -O0 -fstack-protector -fstack-protector-all"
  - CC=gcc-4.6 CFLAGS="-g" VALGRIND=1

install:
  - sudo apt-get update -qq
  - if [ "$VALGRIND" -eq 1 ]; then sudo apt-get install -qq valgrind; export TEST_PHP_ARGS="-m"; fi
  - sudo apt-get install -qq $CC
  - if [ "$VALGRIND" -eq 1 ]; then valgrind --version; fi
  - $CC --version

script:
  - phpize
  - ./configure --enable-igbinary
  # Fix not failing makes in php 5.2 and 5.3
  - perl -i -pe 's/\-\@if/\@if/' Makefile
  - make
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test

branches:
  only:
    - master
